spring.application.name=api-gateway

server.port=${PORT:8080}

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.hostname=localhost

# Route Configuration

spring.cloud.gateway.server.webflux.routes[0].id=test-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://test-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/test/**


## Eureka instance configuration for Render
#eureka.instance.hostname=api-gateway-0twe.onrender.com
#eureka.instance.securePort=443
#eureka.instance.nonSecurePortEnabled=false
#eureka.instance.securePortEnabled=true
