spring.application.name=api-gateway
server.port= ${PORT:8000}

# Route Configuration

spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[1].id=location-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://location-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/address/**

spring.cloud.gateway.server.webflux.routes[2].id=trip-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://tripManagement-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/trips/**

spring.cloud.gateway.server.webflux.routes[3].id=client-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://clientManagement-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/client/**

spring.cloud.gateway.server.webflux.routes[4].id=driver-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://driver-service
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/drivers/**
spring.cloud.gateway.server.webflux.routes[4].predicates[1]=Path=/move-offer/**
spring.cloud.gateway.server.webflux.routes[4].predicates[2]=Path=/vehicle/**