logging.level.org.springframework.cloud.gateway=TRACE
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.cloud.loadbalancer=DEBUG

server.port=8000

spring.application.name=api-gateway

# Routes
spring.cloud.gateway.server.webflux.routes[0].id=auth-service
spring.cloud.gateway.server.webflux.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

spring.cloud.gateway.server.webflux.routes[1].id=user-service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://USER-SERVICE
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**

spring.cloud.gateway.server.webflux.routes[2].id=location-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://LOCATION-SERVICE
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/addresses/**

spring.cloud.gateway.server.webflux.routes[3].id=trip-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://TRIP-SERVICE
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/trips/**

spring.cloud.gateway.server.webflux.routes[4].id=client-service
spring.cloud.gateway.server.webflux.routes[4].uri=lb://CLIENT-SERVICE
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/clients/**

spring.cloud.gateway.server.webflux.routes[5].id=driver-service
spring.cloud.gateway.server.webflux.routes[5].uri=lb://DRIVER-SERVICE
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/drivers/**

spring.cloud.gateway.server.webflux.routes[6].id=payment-service
spring.cloud.gateway.server.webflux.routes[6].uri=lb://PAYMENT-SERVICE
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/payments/**

spring.cloud.gateway.server.webflux.routes[7].id=notification-service
spring.cloud.gateway.server.webflux.routes[7].uri=lb://NOTIFICATION-SERVICE
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/ws-notifications/**

# Global CORS
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedOrigins=http://localhost:3000,http://localhost:5173,https://swiftorg.me,https://api.swiftorg.me
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedMethods=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.corsConfigurations.[/**].allowCredentials=true

# Discovery
spring.cloud.gateway.discovery.locator.enabled=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.enabled=true

# Eureka
eureka.client.enabled=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=${EUREKA_URI:http://eureka-server:8761/eureka/}
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=${HOSTNAME:api-gateway}
