spring.application.name=eureka-server
server.port=${PORT:8761}

# Do not register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=eureka-server

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always
