spring.application.name=driver-service
server.port=${PORT:8061}
spring.config.import=optional:file:../config/application.properties

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
