spring.datasource.url=${NEON_POSTGRES_URI:jdbc:postgresql://localhost:5432/postgres}
spring.datasource.username=${NEON_POSTGRES_USER:postgres}
spring.datasource.password=${NEON_POSTGRES_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql

eureka.instance.prefer-ip-address=true
eureka.client.service-url.default-zone=${EUREKA_URI:http://127.0.0.1:8761/eureka}

application-description=Its Done UK Application
application-license=API Licence
application-version=1.0

# RabbitMQ Configuration
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
