import { User, Driver, Client } from '../types/user';
import { Address } from '../types/address';
import { Vehicle, VehicleType } from '../types/vehicle';
import { MoveRequest } from '../types/move-request';
import { MoveOffer } from '../types/move-offer';
import { MoveTrip } from '../types/trip';
import { LuggageEntry } from '../types/luggage';

// Mock Addresses
const mockAddresses: Address[] = [
  {
    id: '1',
    line1: '123 Main St',
    line2: 'Apt 4B',
    city: 'Toronto',
    stateOrProvince: 'ON',
    postalOrZipCode: 'M5V 3A8',
    country: 'Canada',
    createdAt: '2025-01-01',
    updatedAt: '2025-01-01',
  },
  {
    id: '2',
    line1: '456 Maple Ave',
    city: 'Ottawa',
    stateOrProvince: 'ON',
    postalOrZipCode: 'K1A 0B1',
    country: 'Canada',
    createdAt: '2025-01-02',
    updatedAt: '2025-01-02',
  },
  {
    id: '3',
    line1: '789 Queen St W',
    city: 'Toronto',
    stateOrProvince: 'ON',
    postalOrZipCode: 'M6J 1A7',
    country: 'Canada',
    createdAt: '2025-01-03',
    updatedAt: '2025-01-03',
  },
  {
    id: '4',
    line1: '321 King Rd',
    city: 'Mississauga',
    stateOrProvince: 'ON',
    postalOrZipCode: 'L4Y 2H9',
    country: 'Canada',
    createdAt: '2025-01-04',
    updatedAt: '2025-01-04',
  },
  {
    id: '5',
    line1: '654 Dundas St',
    city: 'Brampton',
    stateOrProvince: 'ON',
    postalOrZipCode: 'L6V 2A3',
    country: 'Canada',
    createdAt: '2025-01-05',
    updatedAt: '2025-01-05',
  },
  {
    id: '6',
    line1: '987 Yonge St',
    city: 'Toronto',
    stateOrProvince: 'ON',
    postalOrZipCode: 'M4W 2K4',
    country: 'Canada',
    createdAt: '2025-01-06',
    updatedAt: '2025-01-06',
  },
  {
    id: '7',
    line1: '111 Bay St',
    city: 'Toronto',
    stateOrProvince: 'ON',
    postalOrZipCode: 'M5H 2R2',
    country: 'Canada',
    createdAt: '2025-01-07',
    updatedAt: '2025-01-07',
  },
  {
    id: '8',
    line1: '222 Adelaide St',
    city: 'Toronto',
    stateOrProvince: 'ON',
    postalOrZipCode: 'M5H 1W7',
    country: 'Canada',
    createdAt: '2025-01-08',
    updatedAt: '2025-01-08',
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    userName: 'john_doe',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    dob: '1990-05-15',
    addressId: '1',
    address: mockAddresses[0],
    createdAt: '2025-01-01',
    updatedAt: '2025-01-15',
  },
  {
    id: '2',
    userName: 'jane_smith',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane@example.com',
    dob: '1992-08-22',
    addressId: '2',
    address: mockAddresses[1],
    createdAt: '2025-01-02',
    updatedAt: '2025-01-14',
  },
  {
    id: '3',
    userName: 'mike_johnson',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'mike@example.com',
    dob: '1988-03-10',
    addressId: '3',
    address: mockAddresses[2],
    createdAt: '2025-01-03',
    updatedAt: '2025-01-13',
  },
  {
    id: '4',
    userName: 'sarah_williams',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah@example.com',
    dob: '1995-11-30',
    addressId: '4',
    address: mockAddresses[3],
    createdAt: '2025-01-04',
    updatedAt: '2025-01-12',
  },
  {
    id: '5',
    userName: 'alex_brown',
    firstName: 'Alex',
    lastName: 'Brown',
    email: 'alex@example.com',
    dob: '1991-07-18',
    addressId: '5',
    address: mockAddresses[4],
    createdAt: '2025-01-05',
    updatedAt: '2025-01-11',
  },
  {
    id: '6',
    userName: 'emma_davis',
    firstName: 'Emma',
    lastName: 'Davis',
    email: 'emma@example.com',
    dob: '1993-09-25',
    addressId: '6',
    address: mockAddresses[5],
    createdAt: '2025-01-06',
    updatedAt: '2025-01-10',
  },
  {
    id: '7',
    userName: 'david_miller',
    firstName: 'David',
    lastName: 'Miller',
    email: 'david@example.com',
    dob: '1989-02-14',
    addressId: '7',
    address: mockAddresses[6],
    createdAt: '2025-01-07',
    updatedAt: '2025-01-09',
  },
  {
    id: '8',
    userName: 'lisa_taylor',
    firstName: 'Lisa',
    lastName: 'Taylor',
    email: 'lisa@example.com',
    dob: '1994-06-08',
    addressId: '8',
    address: mockAddresses[7],
    createdAt: '2025-01-08',
    updatedAt: '2025-01-08',
  },
];

// Mock Drivers
export const mockDrivers: Driver[] = [
  {
    id: '1',
    userId: '1',
    userName: 'john_doe',
    firstName: 'John',
    lastName: 'Doe',
    email: 'john@example.com',
    dob: '1990-05-15',
    addressId: '1',
    address: mockAddresses[0],
    drivingExperience: 10,
    range: 150,
    drivingLicense: 'DL123456789',
    createdAt: '2025-01-01',
    updatedAt: '2025-01-15',
  },
  {
    id: '2',
    userId: '3',
    userName: 'mike_johnson',
    firstName: 'Mike',
    lastName: 'Johnson',
    email: 'mike@example.com',
    dob: '1988-03-10',
    addressId: '3',
    address: mockAddresses[2],
    drivingExperience: 15,
    range: 200,
    drivingLicense: 'DL987654321',
    createdAt: '2025-01-03',
    updatedAt: '2025-01-13',
  },
  {
    id: '3',
    userId: '5',
    userName: 'alex_brown',
    firstName: 'Alex',
    lastName: 'Brown',
    email: 'alex@example.com',
    dob: '1991-07-18',
    addressId: '5',
    address: mockAddresses[4],
    drivingExperience: 8,
    range: 120,
    drivingLicense: 'DL456789123',
    createdAt: '2025-01-05',
    updatedAt: '2025-01-11',
  },
  {
    id: '4',
    userId: '7',
    userName: 'david_miller',
    firstName: 'David',
    lastName: 'Miller',
    email: 'david@example.com',
    dob: '1989-02-14',
    addressId: '7',
    address: mockAddresses[6],
    drivingExperience: 12,
    range: 180,
    drivingLicense: 'DL111222333',
    createdAt: '2025-01-07',
    updatedAt: '2025-01-09',
  },
  {
    id: '5',
    userId: '2',
    userName: 'jane_smith',
    firstName: 'Jane',
    lastName: 'Smith',
    email: 'jane@example.com',
    dob: '1992-08-22',
    addressId: '2',
    address: mockAddresses[1],
    drivingExperience: 7,
    range: 100,
    drivingLicense: 'DL444555666',
    createdAt: '2025-01-02',
    updatedAt: '2025-01-14',
  },
  {
    id: '6',
    userId: '4',
    userName: 'sarah_williams',
    firstName: 'Sarah',
    lastName: 'Williams',
    email: 'sarah@example.com',
    dob: '1995-11-30',
    addressId: '4',
    address: mockAddresses[3],
    drivingExperience: 5,
    range: 90,
    drivingLicense: 'DL777888999',
    createdAt: '2025-01-04',
    updatedAt: '2025-01-12',
  },
];

// Mock Clients
export const mockClients: Client[] = mockUsers
  .filter((_, idx) => idx % 2 === 0)
  .map((user, idx) => ({
    ...user,
    userId: user.id,
    createdAt: user.createdAt || '2025-01-01',
    updatedAt: user.updatedAt || '2025-01-01',
  }));

// Mock Vehicle Types
const mockVehicleTypes: VehicleType[] = [
  { id: '1', type: 'SEDAN', volume: 400, maxWeight: 3000 },
  { id: '2', type: 'SUV', volume: 600, maxWeight: 4500 },
  { id: '3', type: 'VAN', volume: 1000, maxWeight: 5000 },
  { id: '4', type: 'TRUCK', volume: 1500, maxWeight: 6000 },
  { id: '5', type: 'MINIVAN', volume: 800, maxWeight: 4000 },
];

// Mock Vehicles
export const mockVehicles: Vehicle[] = [
  {
    id: '1',
    model: 'Civic',
    make: 'Honda',
    year: 2022,
    color: 'Blue',
    licensePlate: 'HON1234',
    pricePerKm: 1.5,
    isActive: true,
    canCarryFurniture: false,
    driverInfoId: '1',
    vehicleTypeId: '1',
    vehicleType: mockVehicleTypes[0],
    createdAt: '2025-01-01',
    updatedAt: '2025-01-15',
  },
  {
    id: '2',
    model: 'CR-V',
    make: 'Honda',
    year: 2021,
    color: 'Red',
    licensePlate: 'HON5678',
    pricePerKm: 2.0,
    isActive: true,
    canCarryFurniture: true,
    driverInfoId: '2',
    vehicleTypeId: '2',
    vehicleType: mockVehicleTypes[1],
    createdAt: '2025-01-03',
    updatedAt: '2025-01-13',
  },
  {
    id: '3',
    model: 'Transit',
    make: 'Ford',
    year: 2020,
    color: 'White',
    licensePlate: 'FOR9012',
    pricePerKm: 2.5,
    isActive: true,
    canCarryFurniture: true,
    driverInfoId: '3',
    vehicleTypeId: '3',
    vehicleType: mockVehicleTypes[2],
    createdAt: '2025-01-05',
    updatedAt: '2025-01-11',
  },
  {
    id: '4',
    model: 'F-150',
    make: 'Ford',
    year: 2019,
    color: 'Black',
    licensePlate: 'FOR3456',
    pricePerKm: 3.0,
    isActive: true,
    canCarryFurniture: true,
    driverInfoId: '4',
    vehicleTypeId: '4',
    vehicleType: mockVehicleTypes[3],
    createdAt: '2025-01-07',
    updatedAt: '2025-01-09',
  },
  {
    id: '5',
    model: 'Odyssey',
    make: 'Honda',
    year: 2023,
    color: 'Silver',
    licensePlate: 'HON7890',
    pricePerKm: 2.2,
    isActive: true,
    canCarryFurniture: true,
    driverInfoId: '5',
    vehicleTypeId: '5',
    vehicleType: mockVehicleTypes[4],
    createdAt: '2025-01-02',
    updatedAt: '2025-01-14',
  },
  {
    id: '6',
    model: 'Corolla',
    make: 'Toyota',
    year: 2022,
    color: 'Gray',
    licensePlate: 'TOY1234',
    pricePerKm: 1.8,
    isActive: false,
    canCarryFurniture: false,
    driverInfoId: '6',
    vehicleTypeId: '1',
    vehicleType: mockVehicleTypes[0],
    createdAt: '2025-01-04',
    updatedAt: '2025-01-12',
  },
  {
    id: '7',
    model: 'Sprinter',
    make: 'Mercedes',
    year: 2021,
    color: 'White',
    licensePlate: 'MER5678',
    pricePerKm: 3.5,
    isActive: true,
    canCarryFurniture: true,
    driverInfoId: '1',
    vehicleTypeId: '3',
    vehicleType: mockVehicleTypes[2],
    createdAt: '2025-01-06',
    updatedAt: '2025-01-10',
  },
];

// Mock Luggage Entries
const mockLuggageTypes = [
  { id: '1', name: 'Small Box', volume: 50, maxWeight: 25 },
  { id: '2', name: 'Medium Box', volume: 100, maxWeight: 50 },
  { id: '3', name: 'Large Box', volume: 200, maxWeight: 100 },
  { id: '4', name: 'Furniture Piece', volume: 500, maxWeight: 200 },
];

// Mock Move Requests
export const mockMoveRequests: MoveRequest[] = [
  {
    id: '1',
    clientId: '1',
    fromAddressId: '1',
    fromAddress: mockAddresses[0],
    toAddressId: '2',
    toAddress: mockAddresses[1],
    moveDate: '2025-03-15',
    maxBudget: 350,
    status: 'PENDING',
    luggageEntries: [
      { id: '1', quantity: 3, luggageType: mockLuggageTypes[0], luggageTypeId: '1', moveRequestId: '1' },
      { id: '2', quantity: 2, luggageType: mockLuggageTypes[1], luggageTypeId: '2', moveRequestId: '1' },
    ],
    createdAt: '2025-02-20',
    updatedAt: '2025-02-20',
  },
  {
    id: '2',
    clientId: '3',
    fromAddressId: '3',
    fromAddress: mockAddresses[2],
    toAddressId: '4',
    toAddress: mockAddresses[3],
    moveDate: '2025-03-20',
    maxBudget: 500,
    status: 'ACCEPTED',
    luggageEntries: [
      { id: '3', quantity: 5, luggageType: mockLuggageTypes[1], luggageTypeId: '2', moveRequestId: '2' },
      { id: '4', quantity: 1, luggageType: mockLuggageTypes[3], luggageTypeId: '4', moveRequestId: '2' },
    ],
    createdAt: '2025-02-18',
    updatedAt: '2025-02-22',
  },
  {
    id: '3',
    clientId: '5',
    fromAddressId: '5',
    fromAddress: mockAddresses[4],
    toAddressId: '6',
    toAddress: mockAddresses[5],
    moveDate: '2025-03-25',
    maxBudget: 300,
    status: 'PENDING',
    luggageEntries: [
      { id: '5', quantity: 2, luggageType: mockLuggageTypes[0], luggageTypeId: '1', moveRequestId: '3' },
    ],
    createdAt: '2025-02-21',
    updatedAt: '2025-02-21',
  },
  {
    id: '4',
    clientId: '7',
    fromAddressId: '7',
    fromAddress: mockAddresses[6],
    toAddressId: '8',
    toAddress: mockAddresses[7],
    moveDate: '2025-04-01',
    maxBudget: 600,
    status: 'COMPLETED',
    luggageEntries: [
      { id: '6', quantity: 4, luggageType: mockLuggageTypes[1], luggageTypeId: '2', moveRequestId: '4' },
      { id: '7', quantity: 2, luggageType: mockLuggageTypes[2], luggageTypeId: '3', moveRequestId: '4' },
      { id: '8', quantity: 1, luggageType: mockLuggageTypes[3], luggageTypeId: '4', moveRequestId: '4' },
    ],
    createdAt: '2025-02-15',
    updatedAt: '2025-02-22',
  },
  {
    id: '5',
    clientId: '2',
    fromAddressId: '2',
    fromAddress: mockAddresses[1],
    toAddressId: '3',
    toAddress: mockAddresses[2],
    moveDate: '2025-03-10',
    maxBudget: 400,
    status: 'CANCELLED',
    luggageEntries: [
      { id: '9', quantity: 3, luggageType: mockLuggageTypes[1], luggageTypeId: '2', moveRequestId: '5' },
    ],
    createdAt: '2025-02-10',
    updatedAt: '2025-02-22',
  },
  {
    id: '6',
    clientId: '4',
    fromAddressId: '4',
    fromAddress: mockAddresses[3],
    toAddressId: '1',
    toAddress: mockAddresses[0],
    moveDate: '2025-03-30',
    maxBudget: 450,
    status: 'PENDING',
    luggageEntries: [
      { id: '10', quantity: 2, luggageType: mockLuggageTypes[0], luggageTypeId: '1', moveRequestId: '6' },
      { id: '11', quantity: 1, luggageType: mockLuggageTypes[2], luggageTypeId: '3', moveRequestId: '6' },
    ],
    createdAt: '2025-02-19',
    updatedAt: '2025-02-19',
  },
  {
    id: '7',
    clientId: '6',
    fromAddressId: '6',
    fromAddress: mockAddresses[5],
    toAddressId: '7',
    toAddress: mockAddresses[6],
    moveDate: '2025-04-05',
    maxBudget: 550,
    status: 'ACCEPTED',
    luggageEntries: [
      { id: '12', quantity: 6, luggageType: mockLuggageTypes[1], luggageTypeId: '2', moveRequestId: '7' },
    ],
    createdAt: '2025-02-17',
    updatedAt: '2025-02-22',
  },
  {
    id: '8',
    clientId: '8',
    fromAddressId: '8',
    fromAddress: mockAddresses[7],
    toAddressId: '5',
    toAddress: mockAddresses[4],
    moveDate: '2025-03-22',
    maxBudget: 380,
    status: 'PENDING',
    luggageEntries: [
      { id: '13', quantity: 3, luggageType: mockLuggageTypes[0], luggageTypeId: '1', moveRequestId: '8' },
      { id: '14', quantity: 1, luggageType: mockLuggageTypes[3], luggageTypeId: '4', moveRequestId: '8' },
    ],
    createdAt: '2025-02-22',
    updatedAt: '2025-02-22',
  },
];

// Mock Move Offers
export const mockMoveOffers: MoveOffer[] = [
  {
    id: '1',
    moveRequestId: '1',
    moveRequest: mockMoveRequests[0],
    driverId: '1',
    driver: mockDrivers[0],
    vehicleId: '1',
    vehicle: mockVehicles[0],
    price: 300,
    offeredDate: '2025-02-21',
    statusId: '1',
    status: 'PENDING',
    createdAt: '2025-02-21',
    updatedAt: '2025-02-21',
  },
  {
    id: '2',
    moveRequestId: '1',
    moveRequest: mockMoveRequests[0],
    driverId: '2',
    driver: mockDrivers[1],
    vehicleId: '2',
    vehicle: mockVehicles[1],
    price: 320,
    offeredDate: '2025-02-21',
    statusId: '1',
    status: 'ACCEPTED',
    createdAt: '2025-02-21',
    updatedAt: '2025-02-21',
  },
  {
    id: '3',
    moveRequestId: '2',
    moveRequest: mockMoveRequests[1],
    driverId: '3',
    driver: mockDrivers[2],
    vehicleId: '3',
    vehicle: mockVehicles[2],
    price: 450,
    offeredDate: '2025-02-19',
    statusId: '1',
    status: 'PENDING',
    createdAt: '2025-02-19',
    updatedAt: '2025-02-22',
  },
  {
    id: '4',
    moveRequestId: '2',
    moveRequest: mockMoveRequests[1],
    driverId: '4',
    driver: mockDrivers[3],
    vehicleId: '4',
    vehicle: mockVehicles[3],
    price: 480,
    offeredDate: '2025-02-19',
    statusId: '2',
    status: 'REJECTED',
    createdAt: '2025-02-19',
    updatedAt: '2025-02-20',
  },
  {
    id: '5',
    moveRequestId: '4',
    moveRequest: mockMoveRequests[3],
    driverId: '1',
    driver: mockDrivers[0],
    vehicleId: '7',
    vehicle: mockVehicles[6],
    price: 550,
    offeredDate: '2025-02-16',
    statusId: '3',
    status: 'COMPLETED',
    createdAt: '2025-02-16',
    updatedAt: '2025-02-22',
  },
  {
    id: '6',
    moveRequestId: '6',
    moveRequest: mockMoveRequests[5],
    driverId: '5',
    driver: mockDrivers[4],
    vehicleId: '5',
    vehicle: mockVehicles[4],
    price: 400,
    offeredDate: '2025-02-20',
    statusId: '1',
    status: 'PENDING',
    createdAt: '2025-02-20',
    updatedAt: '2025-02-22',
  },
  {
    id: '7',
    moveRequestId: '7',
    moveRequest: mockMoveRequests[6],
    driverId: '2',
    driver: mockDrivers[1],
    vehicleId: '3',
    vehicle: mockVehicles[2],
    price: 520,
    offeredDate: '2025-02-18',
    statusId: '1',
    status: 'ACCEPTED',
    createdAt: '2025-02-18',
    updatedAt: '2025-02-22',
  },
  {
    id: '8',
    moveRequestId: '8',
    moveRequest: mockMoveRequests[7],
    driverId: '6',
    driver: mockDrivers[5],
    vehicleId: '6',
    vehicle: mockVehicles[5],
    price: 350,
    offeredDate: '2025-02-22',
    statusId: '1',
    status: 'PENDING',
    createdAt: '2025-02-22',
    updatedAt: '2025-02-22',
  },
];

// Mock Move Trips
export const mockMoveTrips: MoveTrip[] = [
  {
    id: '1',
    moveRequestId: '4',
    moveRequest: mockMoveRequests[3],
    moveOfferId: '5',
    moveOffer: mockMoveOffers[4],
    driverId: '1',
    driver: mockDrivers[0],
    status: 'COMPLETED',
    startTime: '2025-04-01T08:00:00Z',
    endTime: '2025-04-01T14:30:00Z',
    createdAt: '2025-04-01',
    updatedAt: '2025-04-01',
  },
  {
    id: '2',
    moveRequestId: '1',
    moveRequest: mockMoveRequests[0],
    moveOfferId: '2',
    moveOffer: mockMoveOffers[1],
    driverId: '2',
    driver: mockDrivers[1],
    status: 'ACTIVE',
    startTime: '2025-03-15T09:00:00Z',
    createdAt: '2025-03-15',
    updatedAt: '2025-02-22',
  },
  {
    id: '3',
    moveRequestId: '2',
    moveRequest: mockMoveRequests[1],
    moveOfferId: '3',
    moveOffer: mockMoveOffers[2],
    driverId: '3',
    driver: mockDrivers[2],
    status: 'PENDING',
    createdAt: '2025-02-19',
    updatedAt: '2025-02-22',
  },
  {
    id: '4',
    moveRequestId: '7',
    moveRequest: mockMoveRequests[6],
    moveOfferId: '7',
    moveOffer: mockMoveOffers[6],
    driverId: '2',
    driver: mockDrivers[1],
    status: 'ACTIVE',
    startTime: '2025-04-05T10:00:00Z',
    createdAt: '2025-04-05',
    updatedAt: '2025-02-22',
  },
  {
    id: '5',
    moveRequestId: '3',
    moveRequest: mockMoveRequests[2],
    moveOfferId: '3',
    moveOffer: mockMoveOffers[2],
    driverId: '3',
    driver: mockDrivers[2],
    status: 'PENDING',
    createdAt: '2025-02-22',
    updatedAt: '2025-02-22',
  },
  {
    id: '6',
    moveRequestId: '6',
    moveRequest: mockMoveRequests[5],
    moveOfferId: '6',
    moveOffer: mockMoveOffers[5],
    driverId: '5',
    driver: mockDrivers[4],
    status: 'CANCELLED',
    startTime: '2025-03-30T08:00:00Z',
    endTime: '2025-03-30T09:00:00Z',
    createdAt: '2025-03-30',
    updatedAt: '2025-03-30',
  },
  {
    id: '7',
    moveRequestId: '8',
    moveRequest: mockMoveRequests[7],
    moveOfferId: '8',
    moveOffer: mockMoveOffers[7],
    driverId: '6',
    driver: mockDrivers[5],
    status: 'PENDING',
    createdAt: '2025-02-22',
    updatedAt: '2025-02-22',
  },
  {
    id: '8',
    moveRequestId: '5',
    moveRequest: mockMoveRequests[4],
    moveOfferId: '1',
    moveOffer: mockMoveOffers[0],
    driverId: '1',
    driver: mockDrivers[0],
    status: 'CANCELLED',
    createdAt: '2025-02-10',
    updatedAt: '2025-02-10',
  },
];
