import faker
from faker import Faker

fake = Faker()

# Generate addresses
addresses = []
for i in range(1, 201):
    addr = {
        'id': i,
        'line1': fake.street_address(),
        'line2': fake.secondary_address() if fake.boolean() else '',
        'city': fake.city(),
        'state_or_province': fake.state(),
        'country': 'USA',
        'postal_or_zip_code': fake.zipcode()
    }
    addresses.append(addr)

# Generate users
users = []
roles = ['CLIENT', 'DRIVER', 'ADMIN']
for i in range(1, 81):
    role = fake.random_element(roles)
    user = {
        'id': i,
        'username': fake.user_name(),
        'password_hash': fake.sha256(),
        'f_name': fake.first_name(),
        'l_name': fake.last_name(),
        'dob': fake.date_of_birth(minimum_age=18, maximum_age=80),
        'rating': round(fake.random.uniform(1, 5), 1) if fake.boolean(chance_of_getting_true=70) else None,
        'role': role,
        'address_id': fake.random_int(1, 200)
    }
    users.append(user)

# Driver infos
drivers = [u for u in users if u['role'] == 'DRIVER']
driver_infos = []
for idx, d in enumerate(drivers, 1):
    di = {
        'id': idx,
        'driving_experience': fake.random_int(1, 40),
        'range': fake.random_int(100, 1000),
        'driving_license': fake.license_plate(),
        'user_id': d['id']
    }
    driver_infos.append(di)

# Vehicles
vehicles = []
vid = 1
for d in drivers:
    num_veh = fake.random_int(1, 3)
    for _ in range(num_veh):
        veh = {
            'id': vid,
            'model': fake.word().capitalize(),
            'make': fake.company(),
            'year': fake.year(),
            'color': fake.color_name(),
            'price_per_km': fake.random_int(5, 50),
            'is_active': fake.boolean(),
            'can_carry_furniture': fake.boolean(),
            'driver_id': d['id'],
            'vehicle_type_id': fake.random_int(1, 6)
        }
        vehicles.append(veh)
        vid += 1

# Move requests
clients = [u for u in users if u['role'] == 'CLIENT']
move_requests = []
mrid = 1
statuses = ['CREATED', 'OFFER_SENT', 'OFFER_AVAILABLE', 'PENDING']
for c in clients:
    num_req = fake.random_int(1, 5)
    for _ in range(num_req):
        mr = {
            'id': mrid,
            'move_date': fake.date_time_this_year(),
            'max_budget': fake.random_int(100, 5000),
            'client_id': c['id'],
            'from_address_id': fake.random_int(1, 200),
            'to_address_id': fake.random_int(1, 200),
            'status': fake.random_element(statuses)
        }
        move_requests.append(mr)
        mrid += 1

# Luggage entries
luggage_entries = []
leid = 1
for mr in move_requests:
    num_ent = fake.random_int(1, 10)
    for _ in range(num_ent):
        le = {
            'id': leid,
            'quantity': fake.random_int(1, 20),
            'move_request_id': mr['id'],
            'luggage_type_id': fake.random_int(1, 5)
        }
        luggage_entries.append(le)
        leid += 1

# Move offers
drivers_list = [d['id'] for d in drivers]
vehicles_list = [v['id'] for v in vehicles]
move_offers = []
moid = 1
for mr in move_requests:
    num_off = fake.random_int(1, 5)
    for _ in range(num_off):
        driver_id = fake.random_element(drivers_list)
        veh_for_driver = [v for v in vehicles if v['driver_id'] == driver_id]
        if veh_for_driver:
            veh_id = fake.random_element(veh_for_driver)['id']
        else:
            veh_id = fake.random_element(vehicles_list)
        mo = {
            'id': moid,
            'price': fake.random_int(50, mr['max_budget']),
            'offered_date': fake.date_time_this_year(before_now=True),
            'move_request_id': mr['id'],
            'driver_id': driver_id,
            'vehicle_id': veh_id,
            'status': fake.random_element(statuses)
        }
        move_offers.append(mo)
        moid += 1

# Move trips
move_trips = []
mtid = 1
trip_statuses = ['CONFIRMED', 'PAYMENT_COMPLETED', 'IS_IN_TRANSIT', 'COMPLETED']
for mo in move_offers:
    if fake.boolean(chance_of_getting_true=30):
        mt = {
            'id': mtid,
            'move_request_id': mo['move_request_id'],
            'move_offer_id': mo['id'],
            'status': fake.random_element(trip_statuses)
        }
        move_trips.append(mt)
        mtid += 1

# Write to SQL file
with open('Planning/seed_data.sql', 'w') as f:
    f.write("-- Seed data generated by seed_data.py\n\n")

    # Vehicle types
    f.write("INSERT INTO vehicle_type (id, type, max_weight, capacity) VALUES\n")
    vt_values = [
        "(1, 'SEDAN', 500.0, 4.0)",
        "(2, 'SUV', 800.0, 6.0)",
        "(3, 'HATCHBACKS', 400.0, 4.0)",
        "(4, 'MINIVAN', 600.0, 7.0)",
        "(5, 'VAN', 1000.0, 10.0)",
        "(6, 'TRUCK', 2000.0, 2.0)"
    ]
    f.write(",\n".join(vt_values) + ";\n\n")

    # Luggage types
    f.write("INSERT INTO luggage_type (id, type, name, volume, weight) VALUES\n")
    lt_values = [
        "(1, 'SMALL', 'Small Box', 1.0, 5.0)",
        "(2, 'MEDIUM', 'Medium Box', 2.0, 10.0)",
        "(3, 'LARGE', 'Large Box', 5.0, 20.0)",
        "(4, 'EXTRA_LARGE', 'Extra Large Box', 10.0, 50.0)",
        "(5, 'EXTRA_EXTRA_LARGE', 'Extra Extra Large Box', 20.0, 100.0)"
    ]
    f.write(",\n".join(lt_values) + ";\n\n")

    # Addresses
    f.write("INSERT INTO address (id, line1, line2, city, state_or_province, country, postal_or_zip_code) VALUES\n")
    addr_values = []
    for a in addresses:
        line2 = f"'{a['line2']}'" if a['line2'] else 'NULL'
        val = f"({a['id']}, '{a['line1']}', {line2}, '{a['city']}', '{a['state_or_province']}', '{a['country']}', '{a['postal_or_zip_code']}')"
        addr_values.append(val)
    f.write(",\n".join(addr_values) + ";\n\n")

    # Users
    f.write("INSERT INTO \"user\" (id, username, password_hash, f_name, l_name, dob, rating, role, address_id) VALUES\n")
    user_values = []
    for u in users:
        rating = str(u['rating']) if u['rating'] else 'NULL'
        val = f"({u['id']}, '{u['username']}', '{u['password_hash']}', '{u['f_name']}', '{u['l_name']}', '{u['dob']}', {rating}, '{u['role']}', {u['address_id']})"
        user_values.append(val)
    f.write(",\n".join(user_values) + ";\n\n")

    # Driver infos
    f.write("INSERT INTO driver_info (id, driving_experience, range, driving_license, user_id) VALUES\n")
    di_values = []
    for di in driver_infos:
        val = f"({di['id']}, {di['driving_experience']}, {di['range']}, '{di['driving_license']}', {di['user_id']})"
        di_values.append(val)
    f.write(",\n".join(di_values) + ";\n\n")

    # Vehicles
    f.write("INSERT INTO vehicle (id, model, make, year, color, price_per_km, is_active, can_carry_furniture, driver_id, vehicle_type_id) VALUES\n")
    veh_values = []
    for v in vehicles:
        val = f"({v['id']}, '{v['model']}', '{v['make']}', {v['year']}, '{v['color']}', {v['price_per_km']}, {str(v['is_active']).lower()}, {str(v['can_carry_furniture']).lower()}, {v['driver_id']}, {v['vehicle_type_id']})"
        veh_values.append(val)
    f.write(",\n".join(veh_values) + ";\n\n")

    # Move requests
    f.write("INSERT INTO move_request (id, move_date, max_budget, client_id, from_address_id, to_address_id, status) VALUES\n")
    mr_values = []
    for mr in move_requests:
        val = f"({mr['id']}, '{mr['move_date']}', {mr['max_budget']}, {mr['client_id']}, {mr['from_address_id']}, {mr['to_address_id']}, '{mr['status']}')"
        mr_values.append(val)
    f.write(",\n".join(mr_values) + ";\n\n")

    # Luggage entries
    f.write("INSERT INTO luggage_entry (id, quantity, move_request_id, luggage_type_id) VALUES\n")
    le_values = []
    for le in luggage_entries:
        val = f"({le['id']}, {le['quantity']}, {le['move_request_id']}, {le['luggage_type_id']})"
        le_values.append(val)
    f.write(",\n".join(le_values) + ";\n\n")

    # Move offers
    f.write("INSERT INTO move_offer (id, price, offered_date, move_request_id, driver_id, vehicle_id, status) VALUES\n")
    mo_values = []
    for mo in move_offers:
        val = f"({mo['id']}, {mo['price']}, '{mo['offered_date']}', {mo['move_request_id']}, {mo['driver_id']}, {mo['vehicle_id']}, '{mo['status']}')"
        mo_values.append(val)
    f.write(",\n".join(mo_values) + ";\n\n")

    # Move trips
    f.write("INSERT INTO move_trip (id, move_request_id, move_offer_id, status) VALUES\n")
    mt_values = []
    for mt in move_trips:
        val = f"({mt['id']}, {mt['move_request_id']}, {mt['move_offer_id']}, '{mt['status']}')"
        mt_values.append(val)
    f.write(",\n".join(mt_values) + ";\n\n")

print("Seed data generated in Planning/seed_data.sql")