spring.application.name=payment-service
server.port=8085

# Stripe Configuration
stripe.secret.key=${STRIPE_SECRET_KEY:REPLACE_ME}

# Eureka
eureka.client.serviceUrl.defaultZone=${EUREKA_URI:http://127.0.0.1:8761/eureka}
eureka.instance.prefer-ip-address=true
